version: '3.8'

services:
  # MongoDB service
  mongodb:
    image: mongo:latest
    container_name: marvel-mongodb
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=marvel-explorer
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - marvel-network

  # Backend service
  backend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.backend
    container_name: marvel-backend
    restart: always
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=production
      - PORT=3001
      - MONGODB_URI=mongodb://mongodb:27017/marvel-explorer
      - TMDB_API_KEY=${TMDB_API_KEY}
    ports:
      - "3001:3001"
    networks:
      - marvel-network

  # Frontend service
  frontend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.frontend
      args:
        - REACT_APP_API_URL=${API_URL:-http://localhost:3001}
    container_name: marvel-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - marvel-network

networks:
  marvel-network:
    driver: bridge

volumes:
  mongodb_data:
